# version: '3.8'

# services:
#   opensearch:
#     image: opensearchproject/opensearch:2
#     container_name: opensearch
#     environment:
#       - discovery.type=single-node
#       - DISABLE_SECURITY_PLUGIN=true
#       - DISABLE_INSTALL_DEMO_CONFIG=true
#       - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#       nofile:
#         soft: 65536
#         hard: 65536
#     ports:
#       - "9200:9200"
#       - "9600:9600"
#     volumes:
#       - opensearch-data:/usr/share/opensearch/data

#   opensearch-dashboards:
#     image: opensearchproject/opensearch-dashboards:2
#     container_name: opensearch-dashboards
#     ports:
#       - "5601:5601"
#     environment:
#       - OPENSEARCH_HOSTS=http://opensearch:9200
#       - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
#     depends_on:
#       - opensearch

#   fluentbit:
#     image: fluent/fluent-bit:latest
#     container_name: fluentbit
#     depends_on:
#       - opensearch
#     volumes:
#       - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
#       - ./parsers.conf:/fluent-bit/etc/parsers.conf
#       - ./packages/backend/logs:/packages/backend/logs
#     command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]
#     restart: unless-stopped

# volumes:
#   opensearch-data:

version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - I18N_LOCALE="en"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  fluentbit:
    image: fluent/fluent-bit:latest
    container_name: fluentbit
    depends_on:
      - elasticsearch
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./parsers.conf:/fluent-bit/etc/parsers.conf
      - ./packages/backend/logs:/packages/backend/logs
    command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]
    restart: unless-stopped

volumes:
  elasticsearch-data:
